package com.finance4car.repository.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Finance4carPlanExample {
    /**
     * RudderFramework框架生成代码，请不要直接修改.
     * 
     * This field corresponds to the database table finance4car_plan
     * @generated 2017年11月16日 03:20:53
     */
    protected String orderByClause;

    /**
     * RudderFramework框架生成代码，请不要直接修改.
     * 
     * This field corresponds to the database table finance4car_plan
     * @generated 2017年11月16日 03:20:53
     */
    protected boolean distinct;

    /**
     * RudderFramework框架生成代码，请不要直接修改.
     * 
     * This field corresponds to the database table finance4car_plan
     * @generated 2017年11月16日 03:20:53
     */
    protected List<Criteria> oredCriteria;

    private int startRow;

    private int pageSize;

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_plan
     * @generated 2017年11月16日 03:20:53
     */
    public Finance4carPlanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_plan
     * @generated 2017年11月16日 03:20:53
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_plan
     * @generated 2017年11月16日 03:20:53
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_plan
     * @generated 2017年11月16日 03:20:53
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_plan
     * @generated 2017年11月16日 03:20:53
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_plan
     * @generated 2017年11月16日 03:20:53
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_plan
     * @generated 2017年11月16日 03:20:53
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_plan
     * @generated 2017年11月16日 03:20:53
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_plan
     * @generated 2017年11月16日 03:20:53
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_plan
     * @generated 2017年11月16日 03:20:53
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_plan
     * @generated 2017年11月16日 03:20:53
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setStartRow(int startRow) {
        this.startRow = startRow;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }

    public int getStartRow() {
        return this.startRow;
    }

    public int getPageSize() {
        return this.pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table finance4car_plan
     * @generated 2017年11月16日 03:20:53
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNull() {
            addCriterion("member_id is null");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNotNull() {
            addCriterion("member_id is not null");
            return (Criteria) this;
        }

        public Criteria andMemberIdEqualTo(Long value) {
            addCriterion("member_id =", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotEqualTo(Long value) {
            addCriterion("member_id <>", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThan(Long value) {
            addCriterion("member_id >", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThanOrEqualTo(Long value) {
            addCriterion("member_id >=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThan(Long value) {
            addCriterion("member_id <", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThanOrEqualTo(Long value) {
            addCriterion("member_id <=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIn(List<Long> values) {
            addCriterion("member_id in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotIn(List<Long> values) {
            addCriterion("member_id not in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdBetween(Long value1, Long value2) {
            addCriterion("member_id between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotBetween(Long value1, Long value2) {
            addCriterion("member_id not between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andPlanNameIsNull() {
            addCriterion("plan_name is null");
            return (Criteria) this;
        }

        public Criteria andPlanNameIsNotNull() {
            addCriterion("plan_name is not null");
            return (Criteria) this;
        }

        public Criteria andPlanNameEqualTo(String value) {
            addCriterion("plan_name =", value, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameNotEqualTo(String value) {
            addCriterion("plan_name <>", value, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameGreaterThan(String value) {
            addCriterion("plan_name >", value, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameGreaterThanOrEqualTo(String value) {
            addCriterion("plan_name >=", value, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameLessThan(String value) {
            addCriterion("plan_name <", value, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameLessThanOrEqualTo(String value) {
            addCriterion("plan_name <=", value, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameLike(String value) {
            addCriterion("plan_name like", value, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameNotLike(String value) {
            addCriterion("plan_name not like", value, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameIn(List<String> values) {
            addCriterion("plan_name in", values, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameNotIn(List<String> values) {
            addCriterion("plan_name not in", values, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameBetween(String value1, String value2) {
            addCriterion("plan_name between", value1, value2, "planName");
            return (Criteria) this;
        }

        public Criteria andPlanNameNotBetween(String value1, String value2) {
            addCriterion("plan_name not between", value1, value2, "planName");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNull() {
            addCriterion("department is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNotNull() {
            addCriterion("department is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentEqualTo(String value) {
            addCriterion("department =", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotEqualTo(String value) {
            addCriterion("department <>", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThan(String value) {
            addCriterion("department >", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("department >=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThan(String value) {
            addCriterion("department <", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThanOrEqualTo(String value) {
            addCriterion("department <=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLike(String value) {
            addCriterion("department like", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotLike(String value) {
            addCriterion("department not like", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentIn(List<String> values) {
            addCriterion("department in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotIn(List<String> values) {
            addCriterion("department not in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentBetween(String value1, String value2) {
            addCriterion("department between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotBetween(String value1, String value2) {
            addCriterion("department not between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andCurrentGoalIsNull() {
            addCriterion("current_goal is null");
            return (Criteria) this;
        }

        public Criteria andCurrentGoalIsNotNull() {
            addCriterion("current_goal is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentGoalEqualTo(String value) {
            addCriterion("current_goal =", value, "currentGoal");
            return (Criteria) this;
        }

        public Criteria andCurrentGoalNotEqualTo(String value) {
            addCriterion("current_goal <>", value, "currentGoal");
            return (Criteria) this;
        }

        public Criteria andCurrentGoalGreaterThan(String value) {
            addCriterion("current_goal >", value, "currentGoal");
            return (Criteria) this;
        }

        public Criteria andCurrentGoalGreaterThanOrEqualTo(String value) {
            addCriterion("current_goal >=", value, "currentGoal");
            return (Criteria) this;
        }

        public Criteria andCurrentGoalLessThan(String value) {
            addCriterion("current_goal <", value, "currentGoal");
            return (Criteria) this;
        }

        public Criteria andCurrentGoalLessThanOrEqualTo(String value) {
            addCriterion("current_goal <=", value, "currentGoal");
            return (Criteria) this;
        }

        public Criteria andCurrentGoalLike(String value) {
            addCriterion("current_goal like", value, "currentGoal");
            return (Criteria) this;
        }

        public Criteria andCurrentGoalNotLike(String value) {
            addCriterion("current_goal not like", value, "currentGoal");
            return (Criteria) this;
        }

        public Criteria andCurrentGoalIn(List<String> values) {
            addCriterion("current_goal in", values, "currentGoal");
            return (Criteria) this;
        }

        public Criteria andCurrentGoalNotIn(List<String> values) {
            addCriterion("current_goal not in", values, "currentGoal");
            return (Criteria) this;
        }

        public Criteria andCurrentGoalBetween(String value1, String value2) {
            addCriterion("current_goal between", value1, value2, "currentGoal");
            return (Criteria) this;
        }

        public Criteria andCurrentGoalNotBetween(String value1, String value2) {
            addCriterion("current_goal not between", value1, value2, "currentGoal");
            return (Criteria) this;
        }

        public Criteria andChallengeGoalIsNull() {
            addCriterion("challenge_goal is null");
            return (Criteria) this;
        }

        public Criteria andChallengeGoalIsNotNull() {
            addCriterion("challenge_goal is not null");
            return (Criteria) this;
        }

        public Criteria andChallengeGoalEqualTo(String value) {
            addCriterion("challenge_goal =", value, "challengeGoal");
            return (Criteria) this;
        }

        public Criteria andChallengeGoalNotEqualTo(String value) {
            addCriterion("challenge_goal <>", value, "challengeGoal");
            return (Criteria) this;
        }

        public Criteria andChallengeGoalGreaterThan(String value) {
            addCriterion("challenge_goal >", value, "challengeGoal");
            return (Criteria) this;
        }

        public Criteria andChallengeGoalGreaterThanOrEqualTo(String value) {
            addCriterion("challenge_goal >=", value, "challengeGoal");
            return (Criteria) this;
        }

        public Criteria andChallengeGoalLessThan(String value) {
            addCriterion("challenge_goal <", value, "challengeGoal");
            return (Criteria) this;
        }

        public Criteria andChallengeGoalLessThanOrEqualTo(String value) {
            addCriterion("challenge_goal <=", value, "challengeGoal");
            return (Criteria) this;
        }

        public Criteria andChallengeGoalLike(String value) {
            addCriterion("challenge_goal like", value, "challengeGoal");
            return (Criteria) this;
        }

        public Criteria andChallengeGoalNotLike(String value) {
            addCriterion("challenge_goal not like", value, "challengeGoal");
            return (Criteria) this;
        }

        public Criteria andChallengeGoalIn(List<String> values) {
            addCriterion("challenge_goal in", values, "challengeGoal");
            return (Criteria) this;
        }

        public Criteria andChallengeGoalNotIn(List<String> values) {
            addCriterion("challenge_goal not in", values, "challengeGoal");
            return (Criteria) this;
        }

        public Criteria andChallengeGoalBetween(String value1, String value2) {
            addCriterion("challenge_goal between", value1, value2, "challengeGoal");
            return (Criteria) this;
        }

        public Criteria andChallengeGoalNotBetween(String value1, String value2) {
            addCriterion("challenge_goal not between", value1, value2, "challengeGoal");
            return (Criteria) this;
        }

        public Criteria andSituationIsNull() {
            addCriterion("situation is null");
            return (Criteria) this;
        }

        public Criteria andSituationIsNotNull() {
            addCriterion("situation is not null");
            return (Criteria) this;
        }

        public Criteria andSituationEqualTo(String value) {
            addCriterion("situation =", value, "situation");
            return (Criteria) this;
        }

        public Criteria andSituationNotEqualTo(String value) {
            addCriterion("situation <>", value, "situation");
            return (Criteria) this;
        }

        public Criteria andSituationGreaterThan(String value) {
            addCriterion("situation >", value, "situation");
            return (Criteria) this;
        }

        public Criteria andSituationGreaterThanOrEqualTo(String value) {
            addCriterion("situation >=", value, "situation");
            return (Criteria) this;
        }

        public Criteria andSituationLessThan(String value) {
            addCriterion("situation <", value, "situation");
            return (Criteria) this;
        }

        public Criteria andSituationLessThanOrEqualTo(String value) {
            addCriterion("situation <=", value, "situation");
            return (Criteria) this;
        }

        public Criteria andSituationLike(String value) {
            addCriterion("situation like", value, "situation");
            return (Criteria) this;
        }

        public Criteria andSituationNotLike(String value) {
            addCriterion("situation not like", value, "situation");
            return (Criteria) this;
        }

        public Criteria andSituationIn(List<String> values) {
            addCriterion("situation in", values, "situation");
            return (Criteria) this;
        }

        public Criteria andSituationNotIn(List<String> values) {
            addCriterion("situation not in", values, "situation");
            return (Criteria) this;
        }

        public Criteria andSituationBetween(String value1, String value2) {
            addCriterion("situation between", value1, value2, "situation");
            return (Criteria) this;
        }

        public Criteria andSituationNotBetween(String value1, String value2) {
            addCriterion("situation not between", value1, value2, "situation");
            return (Criteria) this;
        }

        public Criteria andPromotionIsNull() {
            addCriterion("promotion is null");
            return (Criteria) this;
        }

        public Criteria andPromotionIsNotNull() {
            addCriterion("promotion is not null");
            return (Criteria) this;
        }

        public Criteria andPromotionEqualTo(String value) {
            addCriterion("promotion =", value, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionNotEqualTo(String value) {
            addCriterion("promotion <>", value, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionGreaterThan(String value) {
            addCriterion("promotion >", value, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionGreaterThanOrEqualTo(String value) {
            addCriterion("promotion >=", value, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionLessThan(String value) {
            addCriterion("promotion <", value, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionLessThanOrEqualTo(String value) {
            addCriterion("promotion <=", value, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionLike(String value) {
            addCriterion("promotion like", value, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionNotLike(String value) {
            addCriterion("promotion not like", value, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionIn(List<String> values) {
            addCriterion("promotion in", values, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionNotIn(List<String> values) {
            addCriterion("promotion not in", values, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionBetween(String value1, String value2) {
            addCriterion("promotion between", value1, value2, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionNotBetween(String value1, String value2) {
            addCriterion("promotion not between", value1, value2, "promotion");
            return (Criteria) this;
        }

        public Criteria andGrossIncreaseIsNull() {
            addCriterion("gross_increase is null");
            return (Criteria) this;
        }

        public Criteria andGrossIncreaseIsNotNull() {
            addCriterion("gross_increase is not null");
            return (Criteria) this;
        }

        public Criteria andGrossIncreaseEqualTo(String value) {
            addCriterion("gross_increase =", value, "grossIncrease");
            return (Criteria) this;
        }

        public Criteria andGrossIncreaseNotEqualTo(String value) {
            addCriterion("gross_increase <>", value, "grossIncrease");
            return (Criteria) this;
        }

        public Criteria andGrossIncreaseGreaterThan(String value) {
            addCriterion("gross_increase >", value, "grossIncrease");
            return (Criteria) this;
        }

        public Criteria andGrossIncreaseGreaterThanOrEqualTo(String value) {
            addCriterion("gross_increase >=", value, "grossIncrease");
            return (Criteria) this;
        }

        public Criteria andGrossIncreaseLessThan(String value) {
            addCriterion("gross_increase <", value, "grossIncrease");
            return (Criteria) this;
        }

        public Criteria andGrossIncreaseLessThanOrEqualTo(String value) {
            addCriterion("gross_increase <=", value, "grossIncrease");
            return (Criteria) this;
        }

        public Criteria andGrossIncreaseLike(String value) {
            addCriterion("gross_increase like", value, "grossIncrease");
            return (Criteria) this;
        }

        public Criteria andGrossIncreaseNotLike(String value) {
            addCriterion("gross_increase not like", value, "grossIncrease");
            return (Criteria) this;
        }

        public Criteria andGrossIncreaseIn(List<String> values) {
            addCriterion("gross_increase in", values, "grossIncrease");
            return (Criteria) this;
        }

        public Criteria andGrossIncreaseNotIn(List<String> values) {
            addCriterion("gross_increase not in", values, "grossIncrease");
            return (Criteria) this;
        }

        public Criteria andGrossIncreaseBetween(String value1, String value2) {
            addCriterion("gross_increase between", value1, value2, "grossIncrease");
            return (Criteria) this;
        }

        public Criteria andGrossIncreaseNotBetween(String value1, String value2) {
            addCriterion("gross_increase not between", value1, value2, "grossIncrease");
            return (Criteria) this;
        }

        public Criteria andInChargeIsNull() {
            addCriterion("in_charge is null");
            return (Criteria) this;
        }

        public Criteria andInChargeIsNotNull() {
            addCriterion("in_charge is not null");
            return (Criteria) this;
        }

        public Criteria andInChargeEqualTo(String value) {
            addCriterion("in_charge =", value, "inCharge");
            return (Criteria) this;
        }

        public Criteria andInChargeNotEqualTo(String value) {
            addCriterion("in_charge <>", value, "inCharge");
            return (Criteria) this;
        }

        public Criteria andInChargeGreaterThan(String value) {
            addCriterion("in_charge >", value, "inCharge");
            return (Criteria) this;
        }

        public Criteria andInChargeGreaterThanOrEqualTo(String value) {
            addCriterion("in_charge >=", value, "inCharge");
            return (Criteria) this;
        }

        public Criteria andInChargeLessThan(String value) {
            addCriterion("in_charge <", value, "inCharge");
            return (Criteria) this;
        }

        public Criteria andInChargeLessThanOrEqualTo(String value) {
            addCriterion("in_charge <=", value, "inCharge");
            return (Criteria) this;
        }

        public Criteria andInChargeLike(String value) {
            addCriterion("in_charge like", value, "inCharge");
            return (Criteria) this;
        }

        public Criteria andInChargeNotLike(String value) {
            addCriterion("in_charge not like", value, "inCharge");
            return (Criteria) this;
        }

        public Criteria andInChargeIn(List<String> values) {
            addCriterion("in_charge in", values, "inCharge");
            return (Criteria) this;
        }

        public Criteria andInChargeNotIn(List<String> values) {
            addCriterion("in_charge not in", values, "inCharge");
            return (Criteria) this;
        }

        public Criteria andInChargeBetween(String value1, String value2) {
            addCriterion("in_charge between", value1, value2, "inCharge");
            return (Criteria) this;
        }

        public Criteria andInChargeNotBetween(String value1, String value2) {
            addCriterion("in_charge not between", value1, value2, "inCharge");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andProcessModifiedIsNull() {
            addCriterion("process_modified is null");
            return (Criteria) this;
        }

        public Criteria andProcessModifiedIsNotNull() {
            addCriterion("process_modified is not null");
            return (Criteria) this;
        }

        public Criteria andProcessModifiedEqualTo(Boolean value) {
            addCriterion("process_modified =", value, "processModified");
            return (Criteria) this;
        }

        public Criteria andProcessModifiedNotEqualTo(Boolean value) {
            addCriterion("process_modified <>", value, "processModified");
            return (Criteria) this;
        }

        public Criteria andProcessModifiedGreaterThan(Boolean value) {
            addCriterion("process_modified >", value, "processModified");
            return (Criteria) this;
        }

        public Criteria andProcessModifiedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("process_modified >=", value, "processModified");
            return (Criteria) this;
        }

        public Criteria andProcessModifiedLessThan(Boolean value) {
            addCriterion("process_modified <", value, "processModified");
            return (Criteria) this;
        }

        public Criteria andProcessModifiedLessThanOrEqualTo(Boolean value) {
            addCriterion("process_modified <=", value, "processModified");
            return (Criteria) this;
        }

        public Criteria andProcessModifiedIn(List<Boolean> values) {
            addCriterion("process_modified in", values, "processModified");
            return (Criteria) this;
        }

        public Criteria andProcessModifiedNotIn(List<Boolean> values) {
            addCriterion("process_modified not in", values, "processModified");
            return (Criteria) this;
        }

        public Criteria andProcessModifiedBetween(Boolean value1, Boolean value2) {
            addCriterion("process_modified between", value1, value2, "processModified");
            return (Criteria) this;
        }

        public Criteria andProcessModifiedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("process_modified not between", value1, value2, "processModified");
            return (Criteria) this;
        }

        public Criteria andActionModifiedIsNull() {
            addCriterion("action_modified is null");
            return (Criteria) this;
        }

        public Criteria andActionModifiedIsNotNull() {
            addCriterion("action_modified is not null");
            return (Criteria) this;
        }

        public Criteria andActionModifiedEqualTo(Boolean value) {
            addCriterion("action_modified =", value, "actionModified");
            return (Criteria) this;
        }

        public Criteria andActionModifiedNotEqualTo(Boolean value) {
            addCriterion("action_modified <>", value, "actionModified");
            return (Criteria) this;
        }

        public Criteria andActionModifiedGreaterThan(Boolean value) {
            addCriterion("action_modified >", value, "actionModified");
            return (Criteria) this;
        }

        public Criteria andActionModifiedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("action_modified >=", value, "actionModified");
            return (Criteria) this;
        }

        public Criteria andActionModifiedLessThan(Boolean value) {
            addCriterion("action_modified <", value, "actionModified");
            return (Criteria) this;
        }

        public Criteria andActionModifiedLessThanOrEqualTo(Boolean value) {
            addCriterion("action_modified <=", value, "actionModified");
            return (Criteria) this;
        }

        public Criteria andActionModifiedIn(List<Boolean> values) {
            addCriterion("action_modified in", values, "actionModified");
            return (Criteria) this;
        }

        public Criteria andActionModifiedNotIn(List<Boolean> values) {
            addCriterion("action_modified not in", values, "actionModified");
            return (Criteria) this;
        }

        public Criteria andActionModifiedBetween(Boolean value1, Boolean value2) {
            addCriterion("action_modified between", value1, value2, "actionModified");
            return (Criteria) this;
        }

        public Criteria andActionModifiedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("action_modified not between", value1, value2, "actionModified");
            return (Criteria) this;
        }

        public Criteria andImagesIsNull() {
            addCriterion("images is null");
            return (Criteria) this;
        }

        public Criteria andImagesIsNotNull() {
            addCriterion("images is not null");
            return (Criteria) this;
        }

        public Criteria andImagesEqualTo(String value) {
            addCriterion("images =", value, "images");
            return (Criteria) this;
        }

        public Criteria andImagesNotEqualTo(String value) {
            addCriterion("images <>", value, "images");
            return (Criteria) this;
        }

        public Criteria andImagesGreaterThan(String value) {
            addCriterion("images >", value, "images");
            return (Criteria) this;
        }

        public Criteria andImagesGreaterThanOrEqualTo(String value) {
            addCriterion("images >=", value, "images");
            return (Criteria) this;
        }

        public Criteria andImagesLessThan(String value) {
            addCriterion("images <", value, "images");
            return (Criteria) this;
        }

        public Criteria andImagesLessThanOrEqualTo(String value) {
            addCriterion("images <=", value, "images");
            return (Criteria) this;
        }

        public Criteria andImagesLike(String value) {
            addCriterion("images like", value, "images");
            return (Criteria) this;
        }

        public Criteria andImagesNotLike(String value) {
            addCriterion("images not like", value, "images");
            return (Criteria) this;
        }

        public Criteria andImagesIn(List<String> values) {
            addCriterion("images in", values, "images");
            return (Criteria) this;
        }

        public Criteria andImagesNotIn(List<String> values) {
            addCriterion("images not in", values, "images");
            return (Criteria) this;
        }

        public Criteria andImagesBetween(String value1, String value2) {
            addCriterion("images between", value1, value2, "images");
            return (Criteria) this;
        }

        public Criteria andImagesNotBetween(String value1, String value2) {
            addCriterion("images not between", value1, value2, "images");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(Long value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(Long value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(Long value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(Long value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(Long value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(Long value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<Long> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<Long> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(Long value1, Long value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(Long value1, Long value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andLastModifierIsNull() {
            addCriterion("last_modifier is null");
            return (Criteria) this;
        }

        public Criteria andLastModifierIsNotNull() {
            addCriterion("last_modifier is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifierEqualTo(Long value) {
            addCriterion("last_modifier =", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierNotEqualTo(Long value) {
            addCriterion("last_modifier <>", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierGreaterThan(Long value) {
            addCriterion("last_modifier >", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierGreaterThanOrEqualTo(Long value) {
            addCriterion("last_modifier >=", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierLessThan(Long value) {
            addCriterion("last_modifier <", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierLessThanOrEqualTo(Long value) {
            addCriterion("last_modifier <=", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierIn(List<Long> values) {
            addCriterion("last_modifier in", values, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierNotIn(List<Long> values) {
            addCriterion("last_modifier not in", values, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierBetween(Long value1, Long value2) {
            addCriterion("last_modifier between", value1, value2, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierNotBetween(Long value1, Long value2) {
            addCriterion("last_modifier not between", value1, value2, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Boolean value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Boolean value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Boolean value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Boolean value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Boolean> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Boolean> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * RudderFramework Util 生成.
     * 根据数据库表 finance4car_plan
     * @generated do_not_delete_during_merge 2017年11月16日 03:20:53
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table finance4car_plan
     * @generated 2017年11月16日 03:20:53
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}