package com.finance4car.repository.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Finance4carModuleItemExample {
    /**
     * RudderFramework框架生成代码，请不要直接修改.
     * 
     * This field corresponds to the database table finance4car_module_item
     * @generated 2017年11月15日 03:25:33
     */
    protected String orderByClause;

    /**
     * RudderFramework框架生成代码，请不要直接修改.
     * 
     * This field corresponds to the database table finance4car_module_item
     * @generated 2017年11月15日 03:25:33
     */
    protected boolean distinct;

    /**
     * RudderFramework框架生成代码，请不要直接修改.
     * 
     * This field corresponds to the database table finance4car_module_item
     * @generated 2017年11月15日 03:25:33
     */
    protected List<Criteria> oredCriteria;

    private int startRow;

    private int pageSize;

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_module_item
     * @generated 2017年11月15日 03:25:33
     */
    public Finance4carModuleItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_module_item
     * @generated 2017年11月15日 03:25:33
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_module_item
     * @generated 2017年11月15日 03:25:33
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_module_item
     * @generated 2017年11月15日 03:25:33
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_module_item
     * @generated 2017年11月15日 03:25:33
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_module_item
     * @generated 2017年11月15日 03:25:33
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_module_item
     * @generated 2017年11月15日 03:25:33
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_module_item
     * @generated 2017年11月15日 03:25:33
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_module_item
     * @generated 2017年11月15日 03:25:33
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_module_item
     * @generated 2017年11月15日 03:25:33
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  finance4car_module_item
     * @generated 2017年11月15日 03:25:33
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setStartRow(int startRow) {
        this.startRow = startRow;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }

    public int getStartRow() {
        return this.startRow;
    }

    public int getPageSize() {
        return this.pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table finance4car_module_item
     * @generated 2017年11月15日 03:25:33
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andModuleIdIsNull() {
            addCriterion("module_id is null");
            return (Criteria) this;
        }

        public Criteria andModuleIdIsNotNull() {
            addCriterion("module_id is not null");
            return (Criteria) this;
        }

        public Criteria andModuleIdEqualTo(Long value) {
            addCriterion("module_id =", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdNotEqualTo(Long value) {
            addCriterion("module_id <>", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdGreaterThan(Long value) {
            addCriterion("module_id >", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdGreaterThanOrEqualTo(Long value) {
            addCriterion("module_id >=", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdLessThan(Long value) {
            addCriterion("module_id <", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdLessThanOrEqualTo(Long value) {
            addCriterion("module_id <=", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdIn(List<Long> values) {
            addCriterion("module_id in", values, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdNotIn(List<Long> values) {
            addCriterion("module_id not in", values, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdBetween(Long value1, Long value2) {
            addCriterion("module_id between", value1, value2, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdNotBetween(Long value1, Long value2) {
            addCriterion("module_id not between", value1, value2, "moduleId");
            return (Criteria) this;
        }

        public Criteria andItemNameIsNull() {
            addCriterion("item_name is null");
            return (Criteria) this;
        }

        public Criteria andItemNameIsNotNull() {
            addCriterion("item_name is not null");
            return (Criteria) this;
        }

        public Criteria andItemNameEqualTo(String value) {
            addCriterion("item_name =", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotEqualTo(String value) {
            addCriterion("item_name <>", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameGreaterThan(String value) {
            addCriterion("item_name >", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameGreaterThanOrEqualTo(String value) {
            addCriterion("item_name >=", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLessThan(String value) {
            addCriterion("item_name <", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLessThanOrEqualTo(String value) {
            addCriterion("item_name <=", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLike(String value) {
            addCriterion("item_name like", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotLike(String value) {
            addCriterion("item_name not like", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameIn(List<String> values) {
            addCriterion("item_name in", values, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotIn(List<String> values) {
            addCriterion("item_name not in", values, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameBetween(String value1, String value2) {
            addCriterion("item_name between", value1, value2, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotBetween(String value1, String value2) {
            addCriterion("item_name not between", value1, value2, "itemName");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andUnitIsNull() {
            addCriterion("unit is null");
            return (Criteria) this;
        }

        public Criteria andUnitIsNotNull() {
            addCriterion("unit is not null");
            return (Criteria) this;
        }

        public Criteria andUnitEqualTo(String value) {
            addCriterion("unit =", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotEqualTo(String value) {
            addCriterion("unit <>", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThan(String value) {
            addCriterion("unit >", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThanOrEqualTo(String value) {
            addCriterion("unit >=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThan(String value) {
            addCriterion("unit <", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThanOrEqualTo(String value) {
            addCriterion("unit <=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLike(String value) {
            addCriterion("unit like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotLike(String value) {
            addCriterion("unit not like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitIn(List<String> values) {
            addCriterion("unit in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotIn(List<String> values) {
            addCriterion("unit not in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitBetween(String value1, String value2) {
            addCriterion("unit between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotBetween(String value1, String value2) {
            addCriterion("unit not between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andPositionIsNull() {
            addCriterion("position is null");
            return (Criteria) this;
        }

        public Criteria andPositionIsNotNull() {
            addCriterion("position is not null");
            return (Criteria) this;
        }

        public Criteria andPositionEqualTo(Integer value) {
            addCriterion("position =", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotEqualTo(Integer value) {
            addCriterion("position <>", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThan(Integer value) {
            addCriterion("position >", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThanOrEqualTo(Integer value) {
            addCriterion("position >=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThan(Integer value) {
            addCriterion("position <", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThanOrEqualTo(Integer value) {
            addCriterion("position <=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionIn(List<Integer> values) {
            addCriterion("position in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotIn(List<Integer> values) {
            addCriterion("position not in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionBetween(Integer value1, Integer value2) {
            addCriterion("position between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotBetween(Integer value1, Integer value2) {
            addCriterion("position not between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNull() {
            addCriterion("enabled is null");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNotNull() {
            addCriterion("enabled is not null");
            return (Criteria) this;
        }

        public Criteria andEnabledEqualTo(Boolean value) {
            addCriterion("enabled =", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotEqualTo(Boolean value) {
            addCriterion("enabled <>", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThan(Boolean value) {
            addCriterion("enabled >", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThanOrEqualTo(Boolean value) {
            addCriterion("enabled >=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThan(Boolean value) {
            addCriterion("enabled <", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThanOrEqualTo(Boolean value) {
            addCriterion("enabled <=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledIn(List<Boolean> values) {
            addCriterion("enabled in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotIn(List<Boolean> values) {
            addCriterion("enabled not in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledBetween(Boolean value1, Boolean value2) {
            addCriterion("enabled between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotBetween(Boolean value1, Boolean value2) {
            addCriterion("enabled not between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetTypeIsNull() {
            addCriterion("fixed_budget_type is null");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetTypeIsNotNull() {
            addCriterion("fixed_budget_type is not null");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetTypeEqualTo(String value) {
            addCriterion("fixed_budget_type =", value, "fixedBudgetType");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetTypeNotEqualTo(String value) {
            addCriterion("fixed_budget_type <>", value, "fixedBudgetType");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetTypeGreaterThan(String value) {
            addCriterion("fixed_budget_type >", value, "fixedBudgetType");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetTypeGreaterThanOrEqualTo(String value) {
            addCriterion("fixed_budget_type >=", value, "fixedBudgetType");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetTypeLessThan(String value) {
            addCriterion("fixed_budget_type <", value, "fixedBudgetType");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetTypeLessThanOrEqualTo(String value) {
            addCriterion("fixed_budget_type <=", value, "fixedBudgetType");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetTypeLike(String value) {
            addCriterion("fixed_budget_type like", value, "fixedBudgetType");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetTypeNotLike(String value) {
            addCriterion("fixed_budget_type not like", value, "fixedBudgetType");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetTypeIn(List<String> values) {
            addCriterion("fixed_budget_type in", values, "fixedBudgetType");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetTypeNotIn(List<String> values) {
            addCriterion("fixed_budget_type not in", values, "fixedBudgetType");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetTypeBetween(String value1, String value2) {
            addCriterion("fixed_budget_type between", value1, value2, "fixedBudgetType");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetTypeNotBetween(String value1, String value2) {
            addCriterion("fixed_budget_type not between", value1, value2, "fixedBudgetType");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetExpressionIsNull() {
            addCriterion("fixed_budget_expression is null");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetExpressionIsNotNull() {
            addCriterion("fixed_budget_expression is not null");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetExpressionEqualTo(String value) {
            addCriterion("fixed_budget_expression =", value, "fixedBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetExpressionNotEqualTo(String value) {
            addCriterion("fixed_budget_expression <>", value, "fixedBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetExpressionGreaterThan(String value) {
            addCriterion("fixed_budget_expression >", value, "fixedBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetExpressionGreaterThanOrEqualTo(String value) {
            addCriterion("fixed_budget_expression >=", value, "fixedBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetExpressionLessThan(String value) {
            addCriterion("fixed_budget_expression <", value, "fixedBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetExpressionLessThanOrEqualTo(String value) {
            addCriterion("fixed_budget_expression <=", value, "fixedBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetExpressionLike(String value) {
            addCriterion("fixed_budget_expression like", value, "fixedBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetExpressionNotLike(String value) {
            addCriterion("fixed_budget_expression not like", value, "fixedBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetExpressionIn(List<String> values) {
            addCriterion("fixed_budget_expression in", values, "fixedBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetExpressionNotIn(List<String> values) {
            addCriterion("fixed_budget_expression not in", values, "fixedBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetExpressionBetween(String value1, String value2) {
            addCriterion("fixed_budget_expression between", value1, value2, "fixedBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetExpressionNotBetween(String value1, String value2) {
            addCriterion("fixed_budget_expression not between", value1, value2, "fixedBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetPercentIsNull() {
            addCriterion("fixed_budget_percent is null");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetPercentIsNotNull() {
            addCriterion("fixed_budget_percent is not null");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetPercentEqualTo(Boolean value) {
            addCriterion("fixed_budget_percent =", value, "fixedBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetPercentNotEqualTo(Boolean value) {
            addCriterion("fixed_budget_percent <>", value, "fixedBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetPercentGreaterThan(Boolean value) {
            addCriterion("fixed_budget_percent >", value, "fixedBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetPercentGreaterThanOrEqualTo(Boolean value) {
            addCriterion("fixed_budget_percent >=", value, "fixedBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetPercentLessThan(Boolean value) {
            addCriterion("fixed_budget_percent <", value, "fixedBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetPercentLessThanOrEqualTo(Boolean value) {
            addCriterion("fixed_budget_percent <=", value, "fixedBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetPercentIn(List<Boolean> values) {
            addCriterion("fixed_budget_percent in", values, "fixedBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetPercentNotIn(List<Boolean> values) {
            addCriterion("fixed_budget_percent not in", values, "fixedBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetPercentBetween(Boolean value1, Boolean value2) {
            addCriterion("fixed_budget_percent between", value1, value2, "fixedBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andFixedBudgetPercentNotBetween(Boolean value1, Boolean value2) {
            addCriterion("fixed_budget_percent not between", value1, value2, "fixedBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationTypeIsNull() {
            addCriterion("fixed_implementation_type is null");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationTypeIsNotNull() {
            addCriterion("fixed_implementation_type is not null");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationTypeEqualTo(String value) {
            addCriterion("fixed_implementation_type =", value, "fixedImplementationType");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationTypeNotEqualTo(String value) {
            addCriterion("fixed_implementation_type <>", value, "fixedImplementationType");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationTypeGreaterThan(String value) {
            addCriterion("fixed_implementation_type >", value, "fixedImplementationType");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationTypeGreaterThanOrEqualTo(String value) {
            addCriterion("fixed_implementation_type >=", value, "fixedImplementationType");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationTypeLessThan(String value) {
            addCriterion("fixed_implementation_type <", value, "fixedImplementationType");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationTypeLessThanOrEqualTo(String value) {
            addCriterion("fixed_implementation_type <=", value, "fixedImplementationType");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationTypeLike(String value) {
            addCriterion("fixed_implementation_type like", value, "fixedImplementationType");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationTypeNotLike(String value) {
            addCriterion("fixed_implementation_type not like", value, "fixedImplementationType");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationTypeIn(List<String> values) {
            addCriterion("fixed_implementation_type in", values, "fixedImplementationType");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationTypeNotIn(List<String> values) {
            addCriterion("fixed_implementation_type not in", values, "fixedImplementationType");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationTypeBetween(String value1, String value2) {
            addCriterion("fixed_implementation_type between", value1, value2, "fixedImplementationType");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationTypeNotBetween(String value1, String value2) {
            addCriterion("fixed_implementation_type not between", value1, value2, "fixedImplementationType");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationExpressionIsNull() {
            addCriterion("fixed_implementation_expression is null");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationExpressionIsNotNull() {
            addCriterion("fixed_implementation_expression is not null");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationExpressionEqualTo(String value) {
            addCriterion("fixed_implementation_expression =", value, "fixedImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationExpressionNotEqualTo(String value) {
            addCriterion("fixed_implementation_expression <>", value, "fixedImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationExpressionGreaterThan(String value) {
            addCriterion("fixed_implementation_expression >", value, "fixedImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationExpressionGreaterThanOrEqualTo(String value) {
            addCriterion("fixed_implementation_expression >=", value, "fixedImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationExpressionLessThan(String value) {
            addCriterion("fixed_implementation_expression <", value, "fixedImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationExpressionLessThanOrEqualTo(String value) {
            addCriterion("fixed_implementation_expression <=", value, "fixedImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationExpressionLike(String value) {
            addCriterion("fixed_implementation_expression like", value, "fixedImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationExpressionNotLike(String value) {
            addCriterion("fixed_implementation_expression not like", value, "fixedImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationExpressionIn(List<String> values) {
            addCriterion("fixed_implementation_expression in", values, "fixedImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationExpressionNotIn(List<String> values) {
            addCriterion("fixed_implementation_expression not in", values, "fixedImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationExpressionBetween(String value1, String value2) {
            addCriterion("fixed_implementation_expression between", value1, value2, "fixedImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationExpressionNotBetween(String value1, String value2) {
            addCriterion("fixed_implementation_expression not between", value1, value2, "fixedImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationPercentIsNull() {
            addCriterion("fixed_implementation_percent is null");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationPercentIsNotNull() {
            addCriterion("fixed_implementation_percent is not null");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationPercentEqualTo(Boolean value) {
            addCriterion("fixed_implementation_percent =", value, "fixedImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationPercentNotEqualTo(Boolean value) {
            addCriterion("fixed_implementation_percent <>", value, "fixedImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationPercentGreaterThan(Boolean value) {
            addCriterion("fixed_implementation_percent >", value, "fixedImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationPercentGreaterThanOrEqualTo(Boolean value) {
            addCriterion("fixed_implementation_percent >=", value, "fixedImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationPercentLessThan(Boolean value) {
            addCriterion("fixed_implementation_percent <", value, "fixedImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationPercentLessThanOrEqualTo(Boolean value) {
            addCriterion("fixed_implementation_percent <=", value, "fixedImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationPercentIn(List<Boolean> values) {
            addCriterion("fixed_implementation_percent in", values, "fixedImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationPercentNotIn(List<Boolean> values) {
            addCriterion("fixed_implementation_percent not in", values, "fixedImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationPercentBetween(Boolean value1, Boolean value2) {
            addCriterion("fixed_implementation_percent between", value1, value2, "fixedImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andFixedImplementationPercentNotBetween(Boolean value1, Boolean value2) {
            addCriterion("fixed_implementation_percent not between", value1, value2, "fixedImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetTypeIsNull() {
            addCriterion("variable_budget_type is null");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetTypeIsNotNull() {
            addCriterion("variable_budget_type is not null");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetTypeEqualTo(String value) {
            addCriterion("variable_budget_type =", value, "variableBudgetType");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetTypeNotEqualTo(String value) {
            addCriterion("variable_budget_type <>", value, "variableBudgetType");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetTypeGreaterThan(String value) {
            addCriterion("variable_budget_type >", value, "variableBudgetType");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetTypeGreaterThanOrEqualTo(String value) {
            addCriterion("variable_budget_type >=", value, "variableBudgetType");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetTypeLessThan(String value) {
            addCriterion("variable_budget_type <", value, "variableBudgetType");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetTypeLessThanOrEqualTo(String value) {
            addCriterion("variable_budget_type <=", value, "variableBudgetType");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetTypeLike(String value) {
            addCriterion("variable_budget_type like", value, "variableBudgetType");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetTypeNotLike(String value) {
            addCriterion("variable_budget_type not like", value, "variableBudgetType");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetTypeIn(List<String> values) {
            addCriterion("variable_budget_type in", values, "variableBudgetType");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetTypeNotIn(List<String> values) {
            addCriterion("variable_budget_type not in", values, "variableBudgetType");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetTypeBetween(String value1, String value2) {
            addCriterion("variable_budget_type between", value1, value2, "variableBudgetType");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetTypeNotBetween(String value1, String value2) {
            addCriterion("variable_budget_type not between", value1, value2, "variableBudgetType");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetExpressionIsNull() {
            addCriterion("variable_budget_expression is null");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetExpressionIsNotNull() {
            addCriterion("variable_budget_expression is not null");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetExpressionEqualTo(String value) {
            addCriterion("variable_budget_expression =", value, "variableBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetExpressionNotEqualTo(String value) {
            addCriterion("variable_budget_expression <>", value, "variableBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetExpressionGreaterThan(String value) {
            addCriterion("variable_budget_expression >", value, "variableBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetExpressionGreaterThanOrEqualTo(String value) {
            addCriterion("variable_budget_expression >=", value, "variableBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetExpressionLessThan(String value) {
            addCriterion("variable_budget_expression <", value, "variableBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetExpressionLessThanOrEqualTo(String value) {
            addCriterion("variable_budget_expression <=", value, "variableBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetExpressionLike(String value) {
            addCriterion("variable_budget_expression like", value, "variableBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetExpressionNotLike(String value) {
            addCriterion("variable_budget_expression not like", value, "variableBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetExpressionIn(List<String> values) {
            addCriterion("variable_budget_expression in", values, "variableBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetExpressionNotIn(List<String> values) {
            addCriterion("variable_budget_expression not in", values, "variableBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetExpressionBetween(String value1, String value2) {
            addCriterion("variable_budget_expression between", value1, value2, "variableBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetExpressionNotBetween(String value1, String value2) {
            addCriterion("variable_budget_expression not between", value1, value2, "variableBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetPercentIsNull() {
            addCriterion("variable_budget_percent is null");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetPercentIsNotNull() {
            addCriterion("variable_budget_percent is not null");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetPercentEqualTo(Boolean value) {
            addCriterion("variable_budget_percent =", value, "variableBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetPercentNotEqualTo(Boolean value) {
            addCriterion("variable_budget_percent <>", value, "variableBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetPercentGreaterThan(Boolean value) {
            addCriterion("variable_budget_percent >", value, "variableBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetPercentGreaterThanOrEqualTo(Boolean value) {
            addCriterion("variable_budget_percent >=", value, "variableBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetPercentLessThan(Boolean value) {
            addCriterion("variable_budget_percent <", value, "variableBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetPercentLessThanOrEqualTo(Boolean value) {
            addCriterion("variable_budget_percent <=", value, "variableBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetPercentIn(List<Boolean> values) {
            addCriterion("variable_budget_percent in", values, "variableBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetPercentNotIn(List<Boolean> values) {
            addCriterion("variable_budget_percent not in", values, "variableBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetPercentBetween(Boolean value1, Boolean value2) {
            addCriterion("variable_budget_percent between", value1, value2, "variableBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andVariableBudgetPercentNotBetween(Boolean value1, Boolean value2) {
            addCriterion("variable_budget_percent not between", value1, value2, "variableBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationTypeIsNull() {
            addCriterion("variable_implementation_type is null");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationTypeIsNotNull() {
            addCriterion("variable_implementation_type is not null");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationTypeEqualTo(String value) {
            addCriterion("variable_implementation_type =", value, "variableImplementationType");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationTypeNotEqualTo(String value) {
            addCriterion("variable_implementation_type <>", value, "variableImplementationType");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationTypeGreaterThan(String value) {
            addCriterion("variable_implementation_type >", value, "variableImplementationType");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationTypeGreaterThanOrEqualTo(String value) {
            addCriterion("variable_implementation_type >=", value, "variableImplementationType");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationTypeLessThan(String value) {
            addCriterion("variable_implementation_type <", value, "variableImplementationType");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationTypeLessThanOrEqualTo(String value) {
            addCriterion("variable_implementation_type <=", value, "variableImplementationType");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationTypeLike(String value) {
            addCriterion("variable_implementation_type like", value, "variableImplementationType");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationTypeNotLike(String value) {
            addCriterion("variable_implementation_type not like", value, "variableImplementationType");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationTypeIn(List<String> values) {
            addCriterion("variable_implementation_type in", values, "variableImplementationType");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationTypeNotIn(List<String> values) {
            addCriterion("variable_implementation_type not in", values, "variableImplementationType");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationTypeBetween(String value1, String value2) {
            addCriterion("variable_implementation_type between", value1, value2, "variableImplementationType");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationTypeNotBetween(String value1, String value2) {
            addCriterion("variable_implementation_type not between", value1, value2, "variableImplementationType");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationExpressionIsNull() {
            addCriterion("variable_implementation_expression is null");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationExpressionIsNotNull() {
            addCriterion("variable_implementation_expression is not null");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationExpressionEqualTo(String value) {
            addCriterion("variable_implementation_expression =", value, "variableImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationExpressionNotEqualTo(String value) {
            addCriterion("variable_implementation_expression <>", value, "variableImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationExpressionGreaterThan(String value) {
            addCriterion("variable_implementation_expression >", value, "variableImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationExpressionGreaterThanOrEqualTo(String value) {
            addCriterion("variable_implementation_expression >=", value, "variableImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationExpressionLessThan(String value) {
            addCriterion("variable_implementation_expression <", value, "variableImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationExpressionLessThanOrEqualTo(String value) {
            addCriterion("variable_implementation_expression <=", value, "variableImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationExpressionLike(String value) {
            addCriterion("variable_implementation_expression like", value, "variableImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationExpressionNotLike(String value) {
            addCriterion("variable_implementation_expression not like", value, "variableImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationExpressionIn(List<String> values) {
            addCriterion("variable_implementation_expression in", values, "variableImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationExpressionNotIn(List<String> values) {
            addCriterion("variable_implementation_expression not in", values, "variableImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationExpressionBetween(String value1, String value2) {
            addCriterion("variable_implementation_expression between", value1, value2, "variableImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationExpressionNotBetween(String value1, String value2) {
            addCriterion("variable_implementation_expression not between", value1, value2, "variableImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationPercentIsNull() {
            addCriterion("variable_implementation_percent is null");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationPercentIsNotNull() {
            addCriterion("variable_implementation_percent is not null");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationPercentEqualTo(Boolean value) {
            addCriterion("variable_implementation_percent =", value, "variableImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationPercentNotEqualTo(Boolean value) {
            addCriterion("variable_implementation_percent <>", value, "variableImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationPercentGreaterThan(Boolean value) {
            addCriterion("variable_implementation_percent >", value, "variableImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationPercentGreaterThanOrEqualTo(Boolean value) {
            addCriterion("variable_implementation_percent >=", value, "variableImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationPercentLessThan(Boolean value) {
            addCriterion("variable_implementation_percent <", value, "variableImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationPercentLessThanOrEqualTo(Boolean value) {
            addCriterion("variable_implementation_percent <=", value, "variableImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationPercentIn(List<Boolean> values) {
            addCriterion("variable_implementation_percent in", values, "variableImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationPercentNotIn(List<Boolean> values) {
            addCriterion("variable_implementation_percent not in", values, "variableImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationPercentBetween(Boolean value1, Boolean value2) {
            addCriterion("variable_implementation_percent between", value1, value2, "variableImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andVariableImplementationPercentNotBetween(Boolean value1, Boolean value2) {
            addCriterion("variable_implementation_percent not between", value1, value2, "variableImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetTypeIsNull() {
            addCriterion("total_budget_type is null");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetTypeIsNotNull() {
            addCriterion("total_budget_type is not null");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetTypeEqualTo(String value) {
            addCriterion("total_budget_type =", value, "totalBudgetType");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetTypeNotEqualTo(String value) {
            addCriterion("total_budget_type <>", value, "totalBudgetType");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetTypeGreaterThan(String value) {
            addCriterion("total_budget_type >", value, "totalBudgetType");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetTypeGreaterThanOrEqualTo(String value) {
            addCriterion("total_budget_type >=", value, "totalBudgetType");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetTypeLessThan(String value) {
            addCriterion("total_budget_type <", value, "totalBudgetType");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetTypeLessThanOrEqualTo(String value) {
            addCriterion("total_budget_type <=", value, "totalBudgetType");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetTypeLike(String value) {
            addCriterion("total_budget_type like", value, "totalBudgetType");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetTypeNotLike(String value) {
            addCriterion("total_budget_type not like", value, "totalBudgetType");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetTypeIn(List<String> values) {
            addCriterion("total_budget_type in", values, "totalBudgetType");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetTypeNotIn(List<String> values) {
            addCriterion("total_budget_type not in", values, "totalBudgetType");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetTypeBetween(String value1, String value2) {
            addCriterion("total_budget_type between", value1, value2, "totalBudgetType");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetTypeNotBetween(String value1, String value2) {
            addCriterion("total_budget_type not between", value1, value2, "totalBudgetType");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetExpressionIsNull() {
            addCriterion("total_budget_expression is null");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetExpressionIsNotNull() {
            addCriterion("total_budget_expression is not null");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetExpressionEqualTo(String value) {
            addCriterion("total_budget_expression =", value, "totalBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetExpressionNotEqualTo(String value) {
            addCriterion("total_budget_expression <>", value, "totalBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetExpressionGreaterThan(String value) {
            addCriterion("total_budget_expression >", value, "totalBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetExpressionGreaterThanOrEqualTo(String value) {
            addCriterion("total_budget_expression >=", value, "totalBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetExpressionLessThan(String value) {
            addCriterion("total_budget_expression <", value, "totalBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetExpressionLessThanOrEqualTo(String value) {
            addCriterion("total_budget_expression <=", value, "totalBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetExpressionLike(String value) {
            addCriterion("total_budget_expression like", value, "totalBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetExpressionNotLike(String value) {
            addCriterion("total_budget_expression not like", value, "totalBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetExpressionIn(List<String> values) {
            addCriterion("total_budget_expression in", values, "totalBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetExpressionNotIn(List<String> values) {
            addCriterion("total_budget_expression not in", values, "totalBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetExpressionBetween(String value1, String value2) {
            addCriterion("total_budget_expression between", value1, value2, "totalBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetExpressionNotBetween(String value1, String value2) {
            addCriterion("total_budget_expression not between", value1, value2, "totalBudgetExpression");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetPercentIsNull() {
            addCriterion("total_budget_percent is null");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetPercentIsNotNull() {
            addCriterion("total_budget_percent is not null");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetPercentEqualTo(Boolean value) {
            addCriterion("total_budget_percent =", value, "totalBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetPercentNotEqualTo(Boolean value) {
            addCriterion("total_budget_percent <>", value, "totalBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetPercentGreaterThan(Boolean value) {
            addCriterion("total_budget_percent >", value, "totalBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetPercentGreaterThanOrEqualTo(Boolean value) {
            addCriterion("total_budget_percent >=", value, "totalBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetPercentLessThan(Boolean value) {
            addCriterion("total_budget_percent <", value, "totalBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetPercentLessThanOrEqualTo(Boolean value) {
            addCriterion("total_budget_percent <=", value, "totalBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetPercentIn(List<Boolean> values) {
            addCriterion("total_budget_percent in", values, "totalBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetPercentNotIn(List<Boolean> values) {
            addCriterion("total_budget_percent not in", values, "totalBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetPercentBetween(Boolean value1, Boolean value2) {
            addCriterion("total_budget_percent between", value1, value2, "totalBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andTotalBudgetPercentNotBetween(Boolean value1, Boolean value2) {
            addCriterion("total_budget_percent not between", value1, value2, "totalBudgetPercent");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationTypeIsNull() {
            addCriterion("total_implementation_type is null");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationTypeIsNotNull() {
            addCriterion("total_implementation_type is not null");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationTypeEqualTo(String value) {
            addCriterion("total_implementation_type =", value, "totalImplementationType");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationTypeNotEqualTo(String value) {
            addCriterion("total_implementation_type <>", value, "totalImplementationType");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationTypeGreaterThan(String value) {
            addCriterion("total_implementation_type >", value, "totalImplementationType");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationTypeGreaterThanOrEqualTo(String value) {
            addCriterion("total_implementation_type >=", value, "totalImplementationType");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationTypeLessThan(String value) {
            addCriterion("total_implementation_type <", value, "totalImplementationType");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationTypeLessThanOrEqualTo(String value) {
            addCriterion("total_implementation_type <=", value, "totalImplementationType");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationTypeLike(String value) {
            addCriterion("total_implementation_type like", value, "totalImplementationType");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationTypeNotLike(String value) {
            addCriterion("total_implementation_type not like", value, "totalImplementationType");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationTypeIn(List<String> values) {
            addCriterion("total_implementation_type in", values, "totalImplementationType");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationTypeNotIn(List<String> values) {
            addCriterion("total_implementation_type not in", values, "totalImplementationType");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationTypeBetween(String value1, String value2) {
            addCriterion("total_implementation_type between", value1, value2, "totalImplementationType");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationTypeNotBetween(String value1, String value2) {
            addCriterion("total_implementation_type not between", value1, value2, "totalImplementationType");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationExpressionIsNull() {
            addCriterion("total_implementation_expression is null");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationExpressionIsNotNull() {
            addCriterion("total_implementation_expression is not null");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationExpressionEqualTo(String value) {
            addCriterion("total_implementation_expression =", value, "totalImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationExpressionNotEqualTo(String value) {
            addCriterion("total_implementation_expression <>", value, "totalImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationExpressionGreaterThan(String value) {
            addCriterion("total_implementation_expression >", value, "totalImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationExpressionGreaterThanOrEqualTo(String value) {
            addCriterion("total_implementation_expression >=", value, "totalImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationExpressionLessThan(String value) {
            addCriterion("total_implementation_expression <", value, "totalImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationExpressionLessThanOrEqualTo(String value) {
            addCriterion("total_implementation_expression <=", value, "totalImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationExpressionLike(String value) {
            addCriterion("total_implementation_expression like", value, "totalImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationExpressionNotLike(String value) {
            addCriterion("total_implementation_expression not like", value, "totalImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationExpressionIn(List<String> values) {
            addCriterion("total_implementation_expression in", values, "totalImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationExpressionNotIn(List<String> values) {
            addCriterion("total_implementation_expression not in", values, "totalImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationExpressionBetween(String value1, String value2) {
            addCriterion("total_implementation_expression between", value1, value2, "totalImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationExpressionNotBetween(String value1, String value2) {
            addCriterion("total_implementation_expression not between", value1, value2, "totalImplementationExpression");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationPercentIsNull() {
            addCriterion("total_implementation_percent is null");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationPercentIsNotNull() {
            addCriterion("total_implementation_percent is not null");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationPercentEqualTo(Boolean value) {
            addCriterion("total_implementation_percent =", value, "totalImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationPercentNotEqualTo(Boolean value) {
            addCriterion("total_implementation_percent <>", value, "totalImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationPercentGreaterThan(Boolean value) {
            addCriterion("total_implementation_percent >", value, "totalImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationPercentGreaterThanOrEqualTo(Boolean value) {
            addCriterion("total_implementation_percent >=", value, "totalImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationPercentLessThan(Boolean value) {
            addCriterion("total_implementation_percent <", value, "totalImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationPercentLessThanOrEqualTo(Boolean value) {
            addCriterion("total_implementation_percent <=", value, "totalImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationPercentIn(List<Boolean> values) {
            addCriterion("total_implementation_percent in", values, "totalImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationPercentNotIn(List<Boolean> values) {
            addCriterion("total_implementation_percent not in", values, "totalImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationPercentBetween(Boolean value1, Boolean value2) {
            addCriterion("total_implementation_percent between", value1, value2, "totalImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andTotalImplementationPercentNotBetween(Boolean value1, Boolean value2) {
            addCriterion("total_implementation_percent not between", value1, value2, "totalImplementationPercent");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(Long value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(Long value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(Long value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(Long value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(Long value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(Long value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<Long> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<Long> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(Long value1, Long value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(Long value1, Long value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andLastModifierIsNull() {
            addCriterion("last_modifier is null");
            return (Criteria) this;
        }

        public Criteria andLastModifierIsNotNull() {
            addCriterion("last_modifier is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifierEqualTo(Long value) {
            addCriterion("last_modifier =", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierNotEqualTo(Long value) {
            addCriterion("last_modifier <>", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierGreaterThan(Long value) {
            addCriterion("last_modifier >", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierGreaterThanOrEqualTo(Long value) {
            addCriterion("last_modifier >=", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierLessThan(Long value) {
            addCriterion("last_modifier <", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierLessThanOrEqualTo(Long value) {
            addCriterion("last_modifier <=", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierIn(List<Long> values) {
            addCriterion("last_modifier in", values, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierNotIn(List<Long> values) {
            addCriterion("last_modifier not in", values, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierBetween(Long value1, Long value2) {
            addCriterion("last_modifier between", value1, value2, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierNotBetween(Long value1, Long value2) {
            addCriterion("last_modifier not between", value1, value2, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Boolean value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Boolean value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Boolean value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Boolean value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Boolean> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Boolean> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * RudderFramework Util 生成.
     * 根据数据库表 finance4car_module_item
     * @generated do_not_delete_during_merge 2017年11月15日 03:25:33
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table finance4car_module_item
     * @generated 2017年11月15日 03:25:33
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}