spring:
  application:
    name: api-service
  datasource:
    url: jdbc:mysql://47.100.57.236:3306/balabala?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&rewriteBatchedStatements=true
    username: bara
    password: WZCr(P-%2F@R@ZjS
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 47.100.57.236
    port: 6379
    password: 9wCLi7XVozMWttC6

management:
  security:
    enabled: false

security:
  basic:
    enabled: false

mybatis:
  config-location: classpath:mybatis-config.xml

storage:
  local: /data/balabala
  link: http://47.100.57.236:8000

netease:
  app-key: 2dc284c2f3302d1bf2a364a51c957a99
  app-secret: 1076df64c067

debug:
  enabled: true
